# See https://golangci-lint.run/docs/linters/configuration/
version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - err113
    - exhaustive
    - embeddedstructfieldcheck
    - nilnil
    - noinlineerr
    - wsl
    - wsl_v5
    - nlreturn
    - funcorder
    - copyloopvar
    - depguard
    - dupword
    - errname
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - recvcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 20
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    gocognit:
      min-complexity: 45
    misspell:
      locale: US
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 2
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
          - dupl
          - funlen
          - goconst
          - mnd
          - noctx
          - unparam
          - unused
        path: _test.go
      - linters:
          - errcheck
          - gosec
        path: example_
      - linters:
          - revive
        text: 'unused-parameter: parameter'
      - linters:
          - gosec
        text: 'G304: Potential file inclusion via variable'
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/diff
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
